kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lsd-llama-milvus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lsd-llama-milvus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-stack
      app.kubernetes.io/instance: lsd-llama-milvus
  template:
    metadata:
      labels:
        app: llama-stack
        app.kubernetes.io/instance: lsd-llama-milvus
    spec:
      volumes:
        - name: lls-storage
          persistentVolumeClaim:
            claimName: lsd-llama-milvus-pvc
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 12Gi
            requests:
              cpu: 250m
              memory: 500Mi
          terminationMessagePath: /dev/termination-log
          name: llama-stack
          env:
            - name: HF_HOME
              value: /opt/app-root/src/.llama
            - name: INFERENCE_MODEL
              valueFrom:
                secretKeyRef:
                  name: llama-stack-inference-model-secret
                  key: INFERENCE_MODEL
            - name: VLLM_URL
              valueFrom:
                secretKeyRef:
                  name: llama-stack-inference-model-secret
                  key: VLLM_URL
            - name: VLLM_TLS_VERIFY
              valueFrom:
                secretKeyRef:
                  name: llama-stack-inference-model-secret
                  key: VLLM_TLS_VERIFY
            - name: VLLM_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llama-stack-inference-model-secret
                  key: VLLM_API_TOKEN
            - name: MILVUS_DB_PATH
              value: /opt/app-root/src/.llama/milvus.db
            - name: FMS_ORCHESTRATOR_URL
              value: 'http://localhost'
          ports:
            - containerPort: 8321
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: lls-storage
              mountPath: /opt/app-root/src/.llama
          terminationMessagePolicy: File
          image: 'quay.io/opendatahub/llama-stack:odh'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: lsd-llama-milvus-service
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8321
      targetPort: 8321
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: llama-stack
    app.kubernetes.io/instance: lsd-llama-milvus
